version = 0.1
[default.deploy.parameters]
stack_name = "serverless-spring-example"
resolve_s3 = true
s3_prefix = "serverless-spring-example"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
