AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NoMoney Application

Globals:
  Function:
    Timeout: 20

Resources:
  NoMoneyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.NoMoney.LambdaHandler::handleRequest
      Runtime: java21
      SnapStart:
        ApplyOn: PublishedVersions
      MemorySize: 512
      AutoPublishAlias: prod
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        WarmupEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Input: '{"source": "serverless-plugin-warmup"}'
            Name: nomoney-lambda-warmup
            Description: "Keeps the Lambda warm"
            Enabled: true

Outputs:
  NoMoneyApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
